// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfqwuwbggqvuggegbjol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmcXd1d2JnZ3F2dWdnZWdiam9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyODE5MzgsImV4cCI6MjA2Mjg1NzkzOH0.88GBOhYhWsxyPX49n4GOaHD8gVw22YlW6ycMpI_M0MI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);